services:
  - type: web
    name: complaints-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: complaints-db
          property: connectionString
databases:
  - name: complaints-db
